apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-configdb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mongodb-configdb
  resources:
    requests:
      storage: 10Gi
