apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mongodb
  resources:
    requests:
      storage: 10Gi
