apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mysql
  resources:
    requests:
      storage: 10Gi
