apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: redis
  resources:
    requests:
      storage: 10Gi
